
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 74
#define YY_END_OF_BUFFER 75
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[246] =
    {   0,
        0,    0,   75,   73,   73,   73,   71,   72,   63,   61,
       52,   62,   32,   64,    2,   54,   51,   68,   56,   67,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       44,   60,   60,   60,   60,   60,   49,   58,   59,   60,
       73,    0,    0,    2,   55,   53,    0,    2,    0,   50,
       70,   66,   65,   69,   60,   60,   60,   60,   60,   60,
       34,   60,    0,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   43,   60,   60,   60,
       24,   60,   60,   60,   60,   60,   57,   60,    0,    0,
        1,    5,    6,    3,    2,   60,   60,   60,   60,   60,

       60,   35,   36,   38,   37,   60,   60,   60,   60,   60,
       60,   25,   60,   60,   60,   60,   60,   60,   60,   42,
       60,   60,   45,   46,   60,   60,   60,   30,   60,   60,
        1,    3,    0,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   31,   60,   60,   60,   22,    8,   60,   26,   60,
       60,   60,    3,   60,   60,   60,   60,   60,   16,   60,
       60,   60,   60,   39,   60,   60,   60,   23,   27,   60,
       60,   40,   41,   60,   47,   28,   60,   60,   12,   60,
       60,   11,   60,   60,    7,   60,   60,   17,   60,   60,

       29,   60,   60,   60,    0,   60,   60,   60,   60,   13,
       60,   60,   60,   18,   60,   60,    0,    0,   60,    9,
       10,   60,   60,   19,   60,   20,   60,    0,    0,   14,
       33,   60,   21,   48,    0,    0,   15,    0,    0,    4,
        0,    0,    0,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    1,    1,    1,    4,    5,
        6,    7,    8,    9,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,   16,
       17,   18,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   28,   29,   30,   31,   32,   33,
       28,   34,   35,   36,   37,   38,   28,   28,   39,   28,
       40,    1,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   28,   28,   53,   54,   55,
       56,   57,   28,   58,   59,   60,   61,   62,   28,   63,
       64,   28,   65,   66,   67,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[68] =
    {   0,
        1,    2,    1,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    1,    1,    1,    1,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    3,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    3,    1
    } ;

static const flex_int16_t yy_base[250] =
    {   0,
        0,    0,  467,  468,    0,    0,  468,  468,  468,  453,
      468,   55,  449,  468,   58,  442,  468,   57,  438,  435,
       49,   40,   57,   56,   68,  106,    0,   63,   58,   55,
        0,   65,   68,   93,  127,   74,    0,  408,  468,   69,
       65,  444,  442,   92,  468,  468,  431,  108,  430,  468,
      468,  468,  468,  468,    0,  105,  103,  101,  125,  107,
      111,  123,  134,  134,  155,  143,  141,  153,  162,  155,
      159,  158,  168,  169,  168,  170,    0,  161,  190,  168,
        0,  178,  167,  170,  184,  188,  468,  206,  165,  198,
      468,  468,  468,  213,  426,  202,  201,  206,  214,  219,

      208,    0,    0,  468,  218,  224,  223,  209,  216,  226,
      217,    0,  219,  220,  239,  235,  249,  242,  249,    0,
      262,  254,    0,    0,  255,  254,  258,    0,  266,  390,
      277,  277,  424,  259,  258,  271,  265,  277,  267,  272,
      271,  274,  277,  280,  279,  296,  290,  303,  296,  301,
      304,    0,  300,  313,  299,    0,    0,  318,    0,  320,
      321,  372,  421,  315,  314,  329,  330,  315,    0,  322,
      323,  328,  327,    0,  327,  340,  333,    0,    0,  352,
      344,    0,    0,  344,    0,    0,  350,  389,    0,  344,
      350,    0,  359,  349,    0,  357,  356,    0,  357,  356,

        0,  360,  375,  372,   86,  368,  367,  367,  384,    0,
      370,  378,  392,    0,  381,  383,  387,  320,  386,    0,
        0,  387,  394,    0,  391,    0,  395,  297,  260,    0,
        0,  397,    0,    0,  236,  184,    0,   78,   85,  468,
       53,   50,   36,   32,  468,  453,  457,   82,  461
    } ;

static const flex_int16_t yy_def[250] =
    {   0,
      245,    1,  245,  245,  246,  247,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  245,  245,  248,
      249,  245,  247,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  248,  248,  248,  248,  248,  248,
      248,  248,  245,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  245,  248,  249,  249,
      245,  245,  245,  245,  245,  248,  248,  248,  248,  248,

      248,  248,  248,  245,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      249,  245,  245,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  245,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,

      248,  248,  248,  248,  245,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  245,  245,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  245,  245,  248,
      248,  248,  248,  248,  245,  245,  248,  245,  245,  245,
      245,  245,  245,  245,    0,  245,  245,  245,  245
    } ;

static const flex_int16_t yy_nxt[536] =
    {   0,
        4,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   27,   27,   27,   29,
       30,   31,   32,   33,   34,   35,   27,   36,   37,   38,
       39,    4,    4,   21,   22,   23,   24,   25,   26,   27,
       28,   27,   27,   29,   30,   31,   32,   40,   34,   35,
       27,   36,   27,   37,   41,    4,    4,   44,   47,   56,
       48,   58,   45,   51,   52,   59,   90,   57,   61,   63,
       49,   74,   62,   78,   75,   55,   77,  240,   60,   76,
       79,   79,   85,  244,   56,   58,   86,  243,   64,  242,

       59,   57,   47,   61,   48,   49,   74,   62,   78,   75,
       77,   80,   60,   76,   49,   79,   88,   85,   47,   81,
       48,   86,   64,   49,   65,   96,   66,   97,  241,   67,
       49,   91,   98,  240,  217,   68,   80,  101,   69,   49,
       70,   71,   72,   73,   81,   82,   99,  218,  102,   65,
       96,   66,   97,   83,   67,   49,   98,   49,  100,   68,
      103,  101,   69,   84,   70,   71,   72,   73,  104,  105,
       82,   99,  102,   49,  108,  106,   90,  109,   83,  110,
      111,  112,  100,  107,  103,  113,  116,   84,  115,  117,
      119,  120,  104,  105,  121,  114,  124,  125,  108,  126,

      106,  109,  127,  118,  110,  111,  112,  107,  122,   90,
      113,  116,  115,  123,  117,  119,  120,  128,  121,  114,
      124,  129,  125,  126,  122,  132,  127,  118,  134,  123,
      239,   91,  135,  122,  136,  133,  137,  138,  123,  145,
      141,  128,  139,  140,  142,  129,  146,  143,  147,  122,
      148,  149,  150,  134,  123,  130,  135,  144,  136,  151,
      133,  137,  138,  145,  131,  141,  139,  140,  152,  142,
      146,  153,  143,  147,  148,  149,  150,  154,  133,  155,
      156,  144,  157,  158,  151,  159,  160,  161,   90,  132,
      164,  165,  152,  166,  238,  167,  153,  168,  170,  133,

      172,  154,  169,  155,  171,  156,  157,  158,  173,  159,
      160,  174,  161,  175,  164,  165,  176,  236,  166,  167,
      177,  178,  168,  170,  133,  172,  169,  179,  171,  180,
      181,  183,  173,  182,  184,  174,  185,  175,  186,  187,
      190,  176,  133,   91,  177,  189,  178,  191,  192,  235,
      193,  179,  194,  180,  195,  181,  183,  182,  184,  196,
      197,  185,  198,  186,  187,  190,  199,  229,  200,  189,
      201,  204,  191,  192,  193,  202,  194,  203,  195,  206,
      207,  208,  211,  196,  197,  209,  198,  210,  212,  213,
      214,  199,  200,  215,  216,  201,  204,  219,  220,  202,

      221,  203,  222,  206,  207,  223,  208,  211,  224,  209,
      225,  210,  212,  213,  214,  226,  227,  230,  215,  216,
      231,  219,  220,  232,  221,  233,  234,  222,  237,  223,
      228,  205,  224,  163,  188,  225,  163,  162,   95,  226,
      227,  230,   95,   94,  231,   93,   92,  232,   87,  233,
      234,   54,  237,   42,   53,   42,   42,   43,   50,   46,
       43,   89,   89,   89,   89,   44,  245,    3,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245
    } ;

static const flex_int16_t yy_chk[536] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   12,   15,   21,
       15,   22,   12,   18,   18,   23,   41,   21,   24,   25,
       15,   28,   24,   32,   29,  248,   30,  244,   23,   29,
       33,   40,   36,  243,   21,   22,   36,  242,   25,  241,

       23,   21,   44,   24,   44,   15,   28,   24,   32,   29,
       30,   34,   23,   29,   44,   33,   40,   36,   48,   34,
       48,   36,   25,   15,   26,   56,   26,   57,  239,   26,
       48,   41,   58,  238,  205,   26,   34,   60,   26,   44,
       26,   26,   26,   26,   34,   35,   59,  205,   61,   26,
       56,   26,   57,   35,   26,   48,   58,   44,   59,   26,
       62,   60,   26,   35,   26,   26,   26,   26,   63,   64,
       35,   59,   61,   48,   66,   65,   89,   67,   35,   68,
       69,   70,   59,   65,   62,   71,   73,   35,   72,   74,
       75,   76,   63,   64,   78,   71,   80,   82,   66,   83,

       65,   67,   84,   74,   68,   69,   70,   65,   79,   90,
       71,   73,   72,   79,   74,   75,   76,   85,   78,   71,
       80,   86,   82,   83,   88,   94,   84,   74,   96,   88,
      236,   89,   97,   79,   98,   94,   99,  100,   79,  108,
      105,   85,  101,  101,  106,   86,  109,  107,  110,   88,
      111,  113,  114,   96,   88,   88,   97,  107,   98,  115,
       94,   99,  100,  108,   90,  105,  101,  101,  116,  106,
      109,  117,  107,  110,  111,  113,  114,  118,   94,  119,
      121,  107,  122,  125,  115,  126,  127,  129,  131,  132,
      134,  135,  116,  136,  235,  137,  117,  138,  140,  132,

      142,  118,  139,  119,  141,  121,  122,  125,  143,  126,
      127,  144,  129,  145,  134,  135,  146,  229,  136,  137,
      147,  148,  138,  140,  132,  142,  139,  149,  141,  150,
      151,  154,  143,  153,  155,  144,  158,  145,  160,  161,
      165,  146,  132,  131,  147,  164,  148,  166,  167,  228,
      168,  149,  170,  150,  171,  151,  154,  153,  155,  172,
      173,  158,  175,  160,  161,  165,  176,  218,  177,  164,
      180,  187,  166,  167,  168,  181,  170,  184,  171,  190,
      191,  193,  197,  172,  173,  194,  175,  196,  199,  200,
      202,  176,  177,  203,  204,  180,  187,  206,  207,  181,

      208,  184,  209,  190,  191,  211,  193,  197,  212,  194,
      213,  196,  199,  200,  202,  215,  216,  219,  203,  204,
      222,  206,  207,  223,  208,  225,  227,  209,  232,  211,
      217,  188,  212,  163,  162,  213,  133,  130,   95,  215,
      216,  219,   49,   47,  222,   43,   42,  223,   38,  225,
      227,   20,  232,  246,   19,  246,  246,  247,   16,   13,
      247,  249,  249,  249,  249,   10,    3,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/scanner.l"
/**
  * [+] Description: ProAlg Language Scanner
  * [+] Authors: Ruben Cherif & Lorenzo Otermin
  * [+] Date: 28/10/2020
  * [+] GitHub: https://github.com/rabiixx/PDL
  * [+] Version: v1.0
  */
#line 10 "src/scanner.l"

	#include "parser.tab.h"

#line 652 "lex.yy.c"
#line 19 "src/scanner.l"
	/* Special Characters */
	/* Alfabeto */
	/* Literales */
	/* Palabras Reservadas */
	/* Otros Tokens */
	/* Comentarios */
	/* Identificadores */
	/* Operadores Aritmeticos */
	/* Operadores Relacionales */
#line 663 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 131 "src/scanner.l"


#line 883 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 246 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 468 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 133 "src/scanner.l"
{printf("%s - Comentario detectado\n", yytext); return (BI_COMENTARIO); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 135 "src/scanner.l"
{ printf("Literal entero: %d\n", atoi( yytext ) ); return (BI_LIT_ENTERO); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 137 "src/scanner.l"
{ printf("Literal real: %f\n", atof( yytext ) ); return (BI_LIT_REAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 139 "src/scanner.l"
{printf("%s - Booleano\n", yytext); return (BI_LIT_BOOLEANO);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 141 "src/scanner.l"
{printf("%s - Caracter\n", yytext); return (BI_LIT_CARACTER);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 143 "src/scanner.l"
{printf("%s - String\n", yytext); return (BI_LIT_CADENA);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 146 "src/scanner.l"
{printf("%s - Palabra reservada entero detectada \n", yytext); return (BI_PR_ENTERO);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 148 "src/scanner.l"
{printf("%s - Palabra reservada real detectada \n", yytext); return (BI_PR_REAL);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 150 "src/scanner.l"
{printf("%s - Palabra reservada boolenao detectada \n", yytext); return (BI_PR_BOOLEANO);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 152 "src/scanner.l"
{printf("%s - Palabra reservada caracter detectada \n", yytext); return (BI_PR_CARACTER);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 154 "src/scanner.l"
{printf("%s - Palabra reservada cadena detectada \n", yytext); return (BI_PR_CADENA);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 157 "src/scanner.l"
{printf("%s - Palabra reservada accion detectada \n", yytext); return (BI_ACCION);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 158 "src/scanner.l"
{printf("%s - Palabra reservada faccion detectada \n", yytext); return (BI_FACCION);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 160 "src/scanner.l"
{printf("%s - Palabra reservada algoritmo detectada \n", yytext); return (BI_ALGORITMO);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 161 "src/scanner.l"
{printf("%s - Palabra reservada falgoritmo detectada \n", yytext); return (BI_FALGORITMO);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 163 "src/scanner.l"
{printf("%s - Palabra reservada const detectada \n", yytext); return (BI_CONST);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 164 "src/scanner.l"
{printf("%s - Palabra reservada fconst detectada \n", yytext); return (BI_FCONST);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 166 "src/scanner.l"
{printf("%s - Palabra reservada funcion detectada \n", yytext); return (BI_FUNCION);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 167 "src/scanner.l"
{printf("%s - Palabra reservada ffuncion detectada \n", yytext); return (BI_FFUNCION);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 169 "src/scanner.l"
{printf("%s - Palabra reservada mientras detectada \n", yytext); return (BI_MIENTRAS);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 170 "src/scanner.l"
{printf("%s - Palabra reservada fmientras detectada \n", yytext); return (BI_FMIENTRAS);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 172 "src/scanner.l"
{printf("%s - Palabra reservada para detectada \n", yytext); return (BI_PARA);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 173 "src/scanner.l"
{printf("%s - Palabra reservada fpara detectada \n", yytext); return (BI_FPARA);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 175 "src/scanner.l"
{printf("%s - Palabra reservada si detectada \n", yytext); return (BI_SI);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 176 "src/scanner.l"
{printf("%s - Palabra reservada fsi detectada \n", yytext); return (BI_FSI);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 178 "src/scanner.l"
{printf("%s - Palabra reservada tipo detectada \n", yytext); return (BI_TIPO);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 179 "src/scanner.l"
{printf("%s - Palabra reservada ftipo detectada \n", yytext); return (BI_FTIPO);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 181 "src/scanner.l"
{printf("%s - Palabra reservada tupla detectada \n", yytext); return (BI_TUPLA);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 182 "src/scanner.l"
{printf("%s - Palabra reservada ftupla detectada \n", yytext); return (BI_FTUPLA);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 184 "src/scanner.l"
{printf("%s - Palabra reservada var detectada \n", yytext); return (BI_VAR);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 186 "src/scanner.l"
{printf("%s - Palabra reservada fvar detectada \n", yytext); return (BI_FVAR);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 188 "src/scanner.l"
{printf("%s - Token punto \n", yytext); return (BI_PUNTO);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 191 "src/scanner.l"
{printf("%s - Palabra reservada continuar detectada \n", yytext); return (BI_CONTINUAR);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 193 "src/scanner.l"
{printf("%s - Palabra reservada de detectada \n", yytext); return (BI_DE);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 195 "src/scanner.l"
{printf("%s - Palabra reservada dev detectada \n", yytext); return (BI_DEV);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 197 "src/scanner.l"
{printf("%s - Palabra reservada div detectada \n", yytext); return (BI_DIV);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 199 "src/scanner.l"
{printf("%s - Palabra reservada ent detectada \n", yytext); return (BI_ENT);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 201 "src/scanner.l"
{printf("%s - Palabra reservada e/s detectada \n", yytext); return (BI_E_S);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 203 "src/scanner.l"
{printf("%s - Palabra reservada falso detectada \n", yytext); return (BI_FALSO);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 205 "src/scanner.l"
{printf("%s - Palabra reservada hacer detectada \n", yytext); return (BI_HACER);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 207 "src/scanner.l"
{printf("%s - Palabra reservada hasta detectada \n", yytext); return (BI_HASTA);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 209 "src/scanner.l"
{printf("%s - Palabra reservada mod detectada \n", yytext); return (BI_MOD);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 211 "src/scanner.l"
{printf("%s - Palabra reservada no detectada \n", yytext); return (BI_NO);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 213 "src/scanner.l"
{printf("%s - Palabra reservada o detectada \n", yytext); return (BI_O);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 215 "src/scanner.l"
{printf("%s - Palabra reservada ref detectada \n", yytext); return (BI_REF);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 217 "src/scanner.l"
{printf("%s - Palabra reservada sal detectada \n", yytext); return (BI_SAL);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 219 "src/scanner.l"
{printf("%s - Palabra reservada tabla detectada \n", yytext); return (BI_TABLA);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 221 "src/scanner.l"
{printf("%s - Palabra reservada verdadero detectada \n", yytext); return (BI_VERDADERO);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 223 "src/scanner.l"
{printf("%s - Palabra reservada y detectada \n", yytext); return (BI_Y);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 226 "src/scanner.l"
{printf("%s - *Token asignacion(:=) detectada \n", yytext); return (BI_ASIGNACION);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 228 "src/scanner.l"
{printf("%s - *Token composicion sequencial(;) detectada \n", yytext); return (BI_COMP_SEQ);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 230 "src/scanner.l"
{printf("%s - *Token separador(,) detectada \n", yytext); return (BI_SEPARADOR);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 232 "src/scanner.l"
{printf("%s - *Token subrango(..) detectada \n", yytext); return (BI_SUBRANGO);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 234 "src/scanner.l"
{printf("%s - *Token definicion de tipo de variable (:) detectada \n", yytext); return (BI_DEF_TYPEVAR);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 236 "src/scanner.l"
{printf("%s - *Token entonces (->) detectada \n", yytext); return (BI_ENTONCES);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 238 "src/scanner.l"
{printf("%s - *Token creacion de tipo (=) detectada \n", yytext); return (BI_CREACION_TIPO);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 240 "src/scanner.l"
{printf("%s - *Token si no si ([]) detectada \n", yytext); return (BI_SINOSI);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 242 "src/scanner.l"
{printf("%s - *Token inicio array ([) detectada \n", yytext); return (BI_INI_ARRAY);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 244 "src/scanner.l"
{printf("%s - *Token fin array (]) detectada \n", yytext); return (BI_FIN_ARRAY);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 246 "src/scanner.l"
{printf("%s - Identificador\n", yytext); return (BI_IDENTIFICADOR);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 249 "src/scanner.l"
{printf("Operador Aritmetico de Suma: %s\n", yytext); return (BI_SUMA);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 251 "src/scanner.l"
{printf("Operador Aritmetico de Resta: %s\n", yytext); return (BI_RESTA);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 253 "src/scanner.l"
{printf("Operador Aritmetico de Multiplicacion: %s\n", yytext); return (BI_MULTIPLICACION);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 255 "src/scanner.l"
{printf("Operador Aritmetico de Division: %s\n", yytext); return (BI_DIVISION);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 257 "src/scanner.l"
{printf("Operador Relacional Igualdad: %s\n", yytext); return (BI_IGUALDAD);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 259 "src/scanner.l"
{printf("Operador Relacional Distinto: %s\n", yytext); return (BI_DISTINTO);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 261 "src/scanner.l"
{printf("Operador Relacional Mayor: %s\n", yytext); return (BI_MAYOR);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 263 "src/scanner.l"
{printf("Operador Relacional Menor: %s\n", yytext); return (BI_MENOR);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 265 "src/scanner.l"
{printf("Operador Relacional Mayor o Igual: %s\n", yytext); return (BI_MAYOR_IGUAL);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 267 "src/scanner.l"
{printf("Operador Relacional Menor o Igual: %s\n", yytext); return (BI_MENOR_IGUAL);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 269 "src/scanner.l"
{printf("Token parentesis de apertura: %s\n", yytext); return (BI_PAR_APER);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 271 "src/scanner.l"
{printf("Token parentesis de cierre: %s\n", yytext); return (BI_PAR_CIER);}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 275 "src/scanner.l"
{}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 277 "src/scanner.l"
ECHO;
	YY_BREAK
#line 1312 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 246 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 246 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 245);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 277 "src/scanner.l"


/*long int checkPowOverflowInt( int a, int b) {

	for (int i = 0; i < b; ++i)
	    if ( (i * log(a)) >= log(LONG_MAX))
			return -1;

	return (long int) pow(a, b);
}

double checkPowOverflowFloat( double a, double b) {

	for (int i = 0; i < b; ++i)
	    if ( ( i * log( a ) ) >= log( DBL_MAX ) )
			return -1;

	return (double) pow(a, b);
}*/

/*int yywrap(){}
int main(){

	yylex();

	return 0;
}*/
